[package]
name = "transpaer-wikidata"
version = "0.1.0"
edition = "2021"

[dependencies]
bzip2 = { workspace = true }
flate2 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
