[package]
name = "sustainity-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
arangors = { version = "0.5.4", default-features = false, features=["reqwest_async"] }
async-trait = { version = "0.1.24" }
fern = { version = "0.6" }
futures = { version = "0.3.29" }
humantime = { version = "2.1.0" }
hyper = { version = "0.14", features = ["server"] }
log = { version = "0.4.0" }
serde = { version = "1.0", features = ["derive"] }
serde_variant = { version = "0.1.2" }
serde_json = { version = "1.0" }
snafu = { version = "0.7.5" }
swagger = { version = "6.4", features = ["serdejson", "server"] }
tokio = { version = "1.24", features = ["full"] }

sustainity-api = { git = "https://github.com/sustainity-dev/sustainity-api-rust.git", branch = "main", default-features = false, features = ["server"] }
sustainity-models = { path = "../models", features = ["into-api"] }

