[package]
name = "sustainity-condenser"
version = "0.1.0"
edition = "2021"

[dependencies]

clap = { version = "4.1", features = ["derive"] }
log = { version = "0.4" }
fern = { version = "0.6" }

sustainity-condensing = { path = "../condensing" }

