[package]
name = "sustainity-collecting"
version = "0.1.0"
edition = "2021"

[dependencies]

csv = { version = "1.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
serde_yaml = { version = "0.9" }
thiserror = { version = "1.0" }

sustainity-wikidata = { path = "../wikidata" }
