name: CI

on: [push, pull_request]

jobs:

  ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version          

      - name: Format
        run: |
          cargo fmt -- --check

      - name: Check
        run: |
          cargo check
      
      - name: Lint
        run: |
          cargo clippy -- -D warnings         

      - name: Test
        run: |
          cargo test --all          

      - name: Build
        run: |
          cargo build --release          

